export type ToolCategory =
    | "compression"
    | "resize-crop"
    | "conversion"
    | "utilities"
    | "advanced";

export interface HowToStep {
    name: string;
    text: string;
}

export interface ToolFAQ {
    question: string;
    answer: string;
}

export interface ToolData {
    slug: string;
    name: string;
    shortDesc: string;
    extendedDesc?: string;
    category: ToolCategory;
    apiEndpoint: string;
    icon: string;
    metaTitle: string;
    metaDesc: string;
    acceptedFormats: string[];
    outputFormat?: string;
    params?: Record<string, string>;
    isPopular?: boolean;
    isNew?: boolean;
    faqs?: ToolFAQ[];
    howToSteps?: HowToStep[];
}

export const TOOLS: ToolData[] = [
    {
        slug: "compress-image",
        name: "Compress Image",
        shortDesc: "Perceptual compression tuned per image for maximum savings with minimal visible loss.",
        extendedDesc: "Image compression is one of the most effective ways to speed up a website, reduce hosting bandwidth, and improve Google's Core Web Vitals score — specifically Largest Contentful Paint (LCP). PixlTools uses Sharp's perceptual compression engine to analyze each image individually and apply the optimal quality setting, meaning you get the smallest possible file without visible degradation. Unlike many online compressors, PixlTools never upscales or resamples your image — it only removes redundant data, so the output is pixel-accurate at the quality level you choose.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "🗜️",
        metaTitle: "Compress Image Free – Reduce File Size Instantly",
        metaDesc: "Reduce JPG, PNG & WebP file sizes up to 90% instantly. No quality loss, no signup, no watermarks. Try it free — results in seconds.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        isPopular: true,
        howToSteps: [
            { name: "Upload Your Image", text: "Click or drag and drop your JPG, PNG, or WebP image (up to 10 MB) into the upload area." },
            { name: "Adjust Quality", text: "Move the quality slider to balance file size and visual quality. Quality 80 is the sweet spot for most images." },
            { name: "Download Compressed Image", text: "Click Download to save your optimized image. No watermarks are added — ever." },
        ],
        faqs: [
            { question: "How much can you compress an image?", answer: "Most JPEG images can be reduced 60–80% at quality 80 with no visible difference to the human eye." },
            { question: "Is this image compressor free?", answer: "Yes — PixlTools image compression is 100% free with no account or credit card required." },
            { question: "Does compression change the image dimensions?", answer: "No. Compression only reduces file size. Use our Resize Image tool if you need to change pixel dimensions." },
            { question: "What formats can I compress?", answer: "You can compress JPG, PNG, and WebP images. Each format uses the best compression algorithm for that file type." },
            { question: "Is my image stored on your servers?", answer: "No. Images are processed in real-time and deleted immediately. We never store or share your files." },
        ],
    },
    {
        slug: "compress-jpg",
        name: "Compress JPG",
        shortDesc: "Compress JPEG images to reduce file size instantly.",
        extendedDesc: "JPEG is the most widely used image format on the web, and uncompressed or over-sized JPEGs are the single biggest contributor to slow page load times. The JPEG format uses lossy compression based on the Discrete Cosine Transform (DCT), which means you can reduce file size dramatically before quality becomes perceptible to the human eye. At quality 80, a typical JPEG is 60–75% smaller than its full-quality version — cutting both page load time and storage costs — while retaining sharpness and color accuracy that most users cannot distinguish from the original.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "📸",
        metaTitle: "Compress JPG Free – Reduce JPEG Size Up to 80%",
        metaDesc: "Compress JPEG images up to 80% smaller online. Fast, secure, no account needed. Download your optimized JPG in seconds — completely free.",
        acceptedFormats: ["image/jpeg"],
        params: { format: "jpeg" },
        howToSteps: [
            { name: "Upload JPG", text: "Click or drag and drop your JPEG file (up to 10 MB) into the uploader." },
            { name: "Set Quality", text: "Adjust the quality slider. Values between 75–85 give the best balance of size and quality." },
            { name: "Download", text: "Click Download to save your compressed JPG instantly. No watermarks." },
        ],
        faqs: [
            { question: "What quality level should I use for JPEG?", answer: "Quality 80 is the sweet spot — files are 60–75% smaller than the original with virtually no visible loss." },
            { question: "Will compressing JPG reduce visual quality?", answer: "At quality 75–85, the quality loss is imperceptible to the human eye. Only at very low quality (below 60) do compression artifacts become visible." },
            { question: "Can I compress multiple JPG files at once?", answer: "Currently the tool processes one image at a time. For bulk compression, you can process files one after another — all free." },
        ],
    },
    {
        slug: "compress-png",
        name: "Compress PNG",
        shortDesc: "Compress PNG files without losing transparency.",
        extendedDesc: "PNG (Portable Network Graphics) is the web's lossless image format — every pixel is preserved exactly, making it the correct choice for logos, icons, screenshots, and any image that requires transparent backgrounds. The trade-off is file size: an uncompressed PNG of a photograph can be 5–10× larger than an equivalent JPEG. PixlTools optimises PNG files by applying advanced lossless encoding through Sharp, reducing redundant blocks and improving compression metadata without discarding a single pixel of image data. Transparency (alpha channel) is fully preserved, making this tool safe for logos and UI assets that must remain crisp on any background. The result is a smaller file that is byte-for-byte identical in visual quality to the original.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "🖼️",
        metaTitle: "Compress PNG Free – Shrink File Size, Keep Transparency",
        metaDesc: "Compress PNG images online for free. Preserve full transparency while reducing file size significantly. No signup, no watermarks, instant results.",
        acceptedFormats: ["image/png"],
        params: { format: "png" },
        faqs: [
            { question: "Does PNG compression reduce quality?", answer: "No. PNG uses lossless compression — every pixel is preserved exactly. Our tool applies smart encoding to reduce file size without any quality loss." },
            { question: "Will transparency be preserved?", answer: "Yes. Our PNG compressor fully preserves alpha transparency channels." },
            { question: "Why is my PNG still large after compression?", answer: "PNG files for photographs are inherently large because the format is lossless. Try converting to JPEG or WebP for much smaller file sizes, unless you need transparency." },
        ],
    },
    {
        slug: "compress-webp",
        name: "Compress WEBP",
        shortDesc: "Reduce WEBP image file size with optimal compression.",
        extendedDesc: "WebP is already the most efficient general-purpose image format for the web — at the same visual quality, WebP files are 25–35% smaller than JPEG and up to 50% smaller than PNG. But even WebP files can be over-compressed at creation or saved at unnecessarily high quality levels, leaving room for further reduction. PixlTools re-encodes WebP images using Sharp's libwebp integration, applying a smart quality pass that targets the minimum file size achievable before visible quality loss appears. The result lets you squeeze even more efficiency out of a format already designed for the web — directly improving Largest Contentful Paint (LCP) scores and reducing mobile data usage for visitors on metered connections.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "⚡",
        metaTitle: "Compress WebP Free – Smaller Files, Same Quality",
        metaDesc: "Compress WebP images for free. Achieve even smaller file sizes with minimal quality reduction. No account needed — instant results.",
        acceptedFormats: ["image/webp"],
        params: { format: "webp" },
        faqs: [
            { question: "Why should I use WebP instead of JPG?", answer: "WebP images are 25–35% smaller than JPEG at the same visual quality, making them ideal for faster website loading." },
            { question: "Is WebP supported by all browsers?", answer: "Yes — all modern browsers including Chrome, Firefox, Safari 14+, and Edge support WebP, covering over 95% of users." },
            { question: "Can I compress WebP without losing quality?", answer: "At quality 80, WebP compression is nearly lossless to the human eye while delivering significant file size savings." },
        ],
    },
    {
        slug: "resize-image",
        name: "Resize Image",
        shortDesc: "Resize images to any dimension in pixels or percentage.",
        extendedDesc: "Resizing images correctly is critical for both performance and presentation. Serving an image that is larger than its display size wastes bandwidth — a 2400px wide image displayed at 800px forces the browser to download 3× more data than needed, directly hurting your PageSpeed score and Core Web Vitals. PixlTools lets you resize by exact pixel dimensions, percentage, or one of six social media presets (Instagram, YouTube, Twitter, and more), with an optional aspect-ratio lock to prevent distortion. All resizing is done server-side with Lanczos resampling, which produces sharper results than browser-based tools.",
        category: "resize-crop",
        apiEndpoint: "/api/resize",
        icon: "📐",
        metaTitle: "Resize Image Free – Change Size by Pixels or %",
        metaDesc: "Resize images to any dimension online for free. Set exact pixels or scale by percentage. Maintain aspect ratio or set custom dimensions. Instant download.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        isPopular: true,
        howToSteps: [
            { name: "Upload Image", text: "Drag and drop or click to upload your JPG, PNG, or WebP image (up to 10 MB)." },
            { name: "Set New Dimensions", text: "Enter your target width and height in pixels, or enter a percentage to scale proportionally. Toggle 'Maintain Aspect Ratio' to avoid distortion." },
            { name: "Download Resized Image", text: "Click Process, then Download to save your perfectly resized image." },
        ],
        faqs: [
            { question: "Can I resize an image without distorting it?", answer: "Yes — enable 'Maintain Aspect Ratio' and only enter the width or height. The other dimension will scale automatically to avoid distortion." },
            { question: "What is the maximum image size I can resize?", answer: "You can upload images up to 10 MB. There is no restriction on the target dimensions you can resize to." },
            { question: "What formats can I resize?", answer: "You can resize JPG, PNG, and WebP images. The output format matches your input format." },
            { question: "Can I resize an image to a specific percentage?", answer: "Yes — enter a percentage (e.g., 50%) to scale both dimensions proportionally. 50% halves the dimensions and reduces file size by approximately 75%." },
        ],
    },
    {
        slug: "crop-image",
        name: "Crop Image",
        shortDesc: "Crop images to a specific area or aspect ratio.",
        extendedDesc: "Cropping is the most fundamental image editing operation — it lets you remove unwanted areas, change composition, and prepare images for specific aspect ratios required by social platforms. Instagram posts require 1:1 or 4:5, YouTube thumbnails need 16:9, and print photos traditionally use 4:3 or 3:2. PixlTools supports both free-form pixel cropping and locked aspect ratio presets, making it easy to hit the exact dimensions any platform requires without buying desktop software.",
        category: "resize-crop",
        apiEndpoint: "/api/crop",
        icon: "✂️",
        metaTitle: "Crop Image Free – Cut to Any Size or Aspect Ratio",
        metaDesc: "Crop images online for free. Set custom pixel dimensions, choose a preset aspect ratio, or cut a specific area. No signup, instant download.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "Can I crop to a specific aspect ratio?", answer: "Yes — choose presets like 1:1 (square), 16:9, 4:3, or 9:16 for social media, or enter custom pixel dimensions." },
            { question: "Will cropping reduce image quality?", answer: "No. Cropping only removes pixels from the edges — the remaining image content is untouched and retains full quality." },
            { question: "What image formats support cropping?", answer: "You can crop JPG, PNG, and WebP images. PNG files will retain their transparency after cropping." },
        ],
    },
    {
        slug: "rotate-image",
        name: "Rotate Image",
        shortDesc: "Rotate images 90°, 180°, or any custom angle.",
        extendedDesc: "Rotation is one of the most fundamental and frequently needed image editing operations. Smartphone cameras embed an EXIF orientation tag to indicate how a photo should be displayed, but many platforms and applications ignore this tag and display photos sideways or upside-down. Rotating the image pixels directly — rather than relying on the EXIF tag — guarantees the image displays correctly everywhere, regardless of software support. PixlTools supports preset 90°, 180°, and 270° clockwise rotations (which produce no border artifacts) as well as arbitrary custom angles for creative projects and perspective correction. All rotations are processed server-side using Sharp, preserving the original format and quality.",
        category: "resize-crop",
        apiEndpoint: "/api/rotate",
        icon: "🔄",
        metaTitle: "Rotate Image Free Online – 90°, 180° or Any Angle",
        metaDesc: "Rotate images online for free. Rotate 90°, 180°, 270° or enter any custom angle. No signup, no watermarks. Instant result.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "Can I rotate to a custom angle?", answer: "Yes — enter any rotation angle (e.g., 45°, 15°) in the custom angle field. The image will be rotated precisely to that angle." },
            { question: "Will rotating add white borders to my image?", answer: "For preset 90°, 180°, and 270° rotations, no borders are added. For custom angles, some padding may be added to fit the rotated content." },
            { question: "Can I rotate PNG images with transparency?", answer: "Yes. PNG transparency is fully preserved when rotating." },
        ],
    },
    {
        slug: "flip-image",
        name: "Flip Image",
        shortDesc: "Flip images horizontally or vertically online.",
        extendedDesc: "Flipping (mirroring) an image is a lossless operation — no pixels are added, removed, or resampled — making it one of the safest edits you can perform on any image. Horizontal flipping mirrors the image left-to-right, commonly used to create reflections, correct selfie-mirroring (front-facing cameras reverse left and right), or create symmetrical design compositions. Vertical flipping produces an upside-down reflection, useful for creating shadow effects, interface mockups, and stylised social media graphics. PixlTools performs both operations server-side using Sharp, delivering instant results with no quality loss across JPG, PNG, and WebP. Transparency in PNG files is fully preserved during flipping.",
        category: "resize-crop",
        apiEndpoint: "/api/flip",
        icon: "🔀",
        metaTitle: "Flip Image Free Online – Mirror Photo Horizontally or Vertically",
        metaDesc: "Flip or mirror images online for free. Flip horizontally or vertically in one click. No signup, no watermarks. Works on JPG, PNG, WebP.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "What is the difference between flip horizontal and flip vertical?", answer: "Flip horizontal mirrors the image left-to-right (like a mirror). Flip vertical flips the image upside down." },
            { question: "Will flipping affect image quality?", answer: "No. Flipping is a lossless operation — no pixels are added or removed, quality is identical to the original." },
            { question: "Can I flip a PNG with transparency?", answer: "Yes. PNG transparency is fully preserved when flipping." },
        ],
    },
    {
        slug: "jpg-to-png",
        name: "JPG to PNG",
        shortDesc: "Convert JPEG images to PNG format with transparency support.",
        extendedDesc: "Converting from JPG to PNG is necessary when you need to add a transparent background, layer an image over another, or work in a design tool that requires lossless quality. Unlike JPEG, PNG uses lossless compression — meaning every pixel is preserved exactly with no compression artifacts. This is essential for logos, icons, text overlays, and screenshots where crisp edges matter. PixlTools converts JPG to PNG instantly, preserving all color information and enabling full alpha channel support in the output file.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "JPG to PNG Converter Free – Instant, No Signup Required",
        metaDesc: "Convert JPG to PNG online for free. Get full transparency support instantly. No account needed, no watermarks — just fast, clean conversion.",
        acceptedFormats: ["image/jpeg"],
        outputFormat: "png",
        params: { to: "png" },
        faqs: [
            { question: "Why convert JPG to PNG?", answer: "PNG supports transparency and lossless compression, making it ideal for logos, UI graphics, and images that need crisp edges." },
            { question: "Does converting JPG to PNG improve quality?", answer: "Converting to PNG won't recover quality lost during JPEG compression, but the PNG output will not degrade further on repeated saves." },
            { question: "Will the converted PNG have transparency?", answer: "JPEG images don't contain transparency, so the resulting PNG will have a white or solid background from the original JPG." },
        ],
    },
    {
        slug: "png-to-jpg",
        name: "PNG to JPG",
        shortDesc: "Convert PNG images to JPEG format for smaller file sizes.",
        extendedDesc: "PNG's lossless compression is brilliant for graphics and logos, but it produces enormous files when applied to photographs — often 5–10× larger than an equivalent JPEG. If your image is a photo or a complex scene without any transparent areas, converting to JPEG is the single most effective way to dramatically reduce file size. At quality 80, a JPEG photo is typically 60–80% smaller than the same PNG, with a quality difference that is imperceptible to most viewers. PixlTools converts PNG to JPEG server-side using Sharp, merging any transparent areas against a white background (since JPEG does not support alpha channels) and applying a professionally tuned quality setting that balances size and sharpness.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "PNG to JPG Free – Smaller Files, Instant Download",
        metaDesc: "Convert PNG to JPG online for free. Dramatically reduce file size for photos & graphics. No signup, no watermarks. Instant conversion.",
        acceptedFormats: ["image/png"],
        outputFormat: "jpeg",
        params: { to: "jpeg" },
        faqs: [
            { question: "Why convert PNG to JPG?", answer: "JPG files are far smaller than PNG for photographs — often 60–80% smaller — making them faster to load and easier to share." },
            { question: "What happens to PNG transparency when converted?", answer: "JPEG doesn't support transparency, so transparent areas will be filled with a white background during conversion." },
            { question: "Will converting PNG to JPG reduce quality?", answer: "JPEG uses lossy compression, so some quality is lost. At quality 80, the difference is imperceptible for most photos." },
        ],
    },
    {
        slug: "jpg-to-webp",
        name: "JPG to WEBP",
        shortDesc: "Convert JPEG images to modern WEBP format.",
        extendedDesc: "WebP is Google's modern image format, designed to replace JPEG for photographs on the web. At the same visual quality, WebP files are 25-35% smaller than JPEG — a massive improvement that directly reduces bandwidth usage and improves Largest Contentful Paint (LCP), a key Core Web Vitals metric. All major browsers — Chrome, Firefox, Safari (14+), and Edge — support WebP natively. Converting your JPG library to WebP is one of the highest-impact, lowest-effort performance improvements you can make to a website.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "JPG to WebP Free – Shrink Photos 30%, No Signup",
        metaDesc: "Convert JPG to WebP and reduce file size by up to 30% with zero quality loss. Free, instant, no account. Google's modern web image format.",
        acceptedFormats: ["image/jpeg"],
        outputFormat: "webp",
        params: { to: "webp" },
        howToSteps: [
            { name: "Upload JPG", text: "Drag and drop or click to upload your JPEG image (up to 10 MB)." },
            { name: "Convert", text: "Click the Process button. Your image is automatically converted to WebP format." },
            { name: "Download WebP", text: "Download your converted WebP file. It will be 25–35% smaller than the original JPG." },
        ],
        faqs: [
            { question: "Why convert JPG to WebP?", answer: "WebP images are 25–35% smaller than JPEG at identical visual quality, making your website load faster and improving Google Core Web Vitals scores." },
            { question: "Is WebP supported by all browsers?", answer: "Yes — Chrome, Firefox, Safari 14+, Edge, and Opera all support WebP, covering over 95% of web users worldwide." },
            { question: "Does converting to WebP lose quality?", answer: "At the default quality setting (80), the quality difference from JPEG is virtually imperceptible while the file size decreases significantly." },
        ],
    },
    {
        slug: "webp-to-jpg",
        name: "WEBP to JPG",
        shortDesc: "Convert WEBP images to universally supported JPEG.",
        extendedDesc: "WebP is the modern standard for web images, but compatibility outside the browser remains limited — many desktop applications, email clients, content management systems, and enterprise tools still cannot read WebP files natively. Converting to JPEG makes an image universally compatible: every device, operating system, app, and email client that has existed since the early 1990s can open a JPEG file. PixlTools converts WebP to JPEG server-side using Sharp's high-fidelity decoder, preserving colour accuracy across the entire tonal range. The output retains the visual quality of the original WebP file while giving you a file that can be opened anywhere — from Photoshop to Windows Photo Viewer to Gmail attachments.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "WebP to JPG Free – Convert to JPEG Instantly",
        metaDesc: "Convert WebP to JPG online for free. Make WebP images compatible with all devices, apps, and email clients. No signup, no watermarks.",
        acceptedFormats: ["image/webp"],
        outputFormat: "jpeg",
        params: { to: "jpeg" },
        faqs: [
            { question: "Why convert WebP to JPG?", answer: "While WebP is supported by modern browsers, some older apps, email clients, and editing software don't support it. JPG is universally compatible." },
            { question: "Will the converted JPG be lower quality?", answer: "At our default quality setting, the visual difference is negligible. JPEG is an excellent format for sharing and compatibility." },
            { question: "Can I open the converted JPG in Photoshop or Lightroom?", answer: "Yes — JPEG is fully supported by all major photo editing applications including Photoshop, Lightroom, and GIMP." },
        ],
    },
    {
        slug: "png-to-webp",
        name: "PNG to WEBP",
        shortDesc: "Convert PNG images to WEBP for better web performance.",
        extendedDesc: "WebP was designed by Google as a unified replacement for both JPEG and PNG on the web. For lossless content like logos, icons, and screenshots, WebP lossless encoding is typically 25% smaller than an equivalent PNG. For photographic content, switching to WebP lossy encoding can reduce file size by 30–50% compared to PNG, while retaining transparency support that PNG users depend on. This makes PNG-to-WebP conversion a high-value optimisation for web developers: you eliminate the need for separate JPEG (for photos) and PNG (for transparency) strategies and serve a single, smaller, modern format. All modern browsers including Chrome, Firefox, Safari 14+, and Edge support WebP natively — covering over 97% of users worldwide.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "PNG to WebP Free – Faster Web Images, Instant Convert",
        metaDesc: "Convert PNG to WebP online for free. Get smaller file sizes with the same quality for faster-loading websites. No account, no watermarks.",
        acceptedFormats: ["image/png"],
        outputFormat: "webp",
        params: { to: "webp" },
        faqs: [
            { question: "Can WebP replace PNG for web use?", answer: "Yes — WebP supports both lossless and lossy compression, as well as transparency (alpha channel), making it a perfect PNG replacement for web use." },
            { question: "Will my PNG transparency be kept in WebP?", answer: "Yes. WebP fully supports transparency (alpha channel), just like PNG." },
            { question: "How much smaller will the WebP be compared to PNG?", answer: "For photographs, WebP is typically 30–50% smaller. For graphics and logos, savings range from 10–25%." },
        ],
    },
    {
        slug: "webp-to-png",
        name: "WEBP to PNG",
        shortDesc: "Convert WEBP images to PNG format with lossless output.",
        extendedDesc: "While WebP is the optimal format for web delivery, there are situations where PNG is the correct target — particularly when you need lossless quality for editing workflows, pixel-perfect archival, or compatibility with professional design tools that do not yet support WebP. Converting a lossless WebP to PNG results in a file that is byte-for-byte identical in visual quality to the source, fully editable in Photoshop, Figma, GIMP, Affinity Photo, and all major design applications. PixlTools performs this conversion server-side using Sharp, decoding the WebP and re-encoding as PNG to ISO standard, with full alpha transparency preservation. The output is suitable for professional pre-press workflows, client deliverables requiring non-web formats, and archival purposes.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "WebP to PNG Free – Lossless Conversion, No Signup",
        metaDesc: "Convert WebP to PNG online for free. Get a lossless PNG with full alpha transparency. Instant download, no account required.",
        acceptedFormats: ["image/webp"],
        outputFormat: "png",
        params: { to: "png" },
        faqs: [
            { question: "Why convert WebP to PNG?", answer: "PNG is needed when lossless quality is critical — for editing, printing, or use in applications that require pixel-perfect graphics." },
            { question: "Is WebP to PNG conversion lossless?", answer: "Yes. When converting a lossless WebP to PNG, no quality is lost. For lossy WebP source files, the quality matches the original WebP." },
            { question: "Will transparency be preserved?", answer: "Yes. Both WebP and PNG support full alpha transparency, which is preserved during conversion." },
        ],
    },
    {
        slug: "image-to-pdf",
        name: "Image to PDF",
        shortDesc: "Convert JPG, PNG, or WEBP images to PDF documents.",
        extendedDesc: "PDF is the world's most universally accepted document format — required by government portals, employers, universities, and businesses everywhere. Converting your images to PDF is the fastest way to make photos submission-ready without installing any software. PixlTools converts JPG, PNG, and WebP images into clean, properly-formatted PDF documents server-side in seconds. The output PDF is compatible with Adobe Acrobat, Google Docs, email clients, and all major operating systems. Unlike many online converters, PixlTools adds no watermarks, no branding, and no compression artifacts — your image appears in the PDF exactly as uploaded. This tool is especially useful for ID photo submissions, portfolio documents, and converting product images to printable formats.",
        category: "utilities",
        apiEndpoint: "/api/image-to-pdf",
        icon: "📄",
        metaTitle: "Image to PDF Free – Convert JPG/PNG to PDF Instantly",
        metaDesc: "Convert images to PDF online for free. Turn JPG, PNG, or WebP into a PDF document instantly. No software, no signup, no watermarks.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        outputFormat: "pdf",
        howToSteps: [
            { name: "Upload Your Image", text: "Click or drag and drop your JPG, PNG, or WebP image (up to 10 MB) into the upload area." },
            { name: "Convert to PDF", text: "Click the Process button. Your image is instantly converted into a properly-formatted PDF document on our secure servers." },
            { name: "Download PDF", text: "Click Download to save your PDF. No watermarks, no account needed — the file is yours immediately." },
        ],
        faqs: [
            { question: "What image formats can I convert to PDF?", answer: "You can convert JPG, PNG, and WebP images to PDF. All common web image formats are supported." },
            { question: "Is the PDF quality good for printing?", answer: "Yes — the PDF is generated at high quality suitable for digital submission. For professional print, start with a high-resolution source image (300 DPI or above)." },
            { question: "Can I convert multiple images into one PDF?", answer: "Our online tool converts one image per PDF. For multi-image PDFs, you can merge the resulting PDFs using a free PDF merger tool." },
            { question: "Will my PDF have watermarks?", answer: "Absolutely not. All PixlTools outputs are 100% watermark-free." },
        ],
    },
    {
        slug: "pdf-to-image",
        name: "PDF to Image",
        shortDesc: "Extract PDF pages and convert them to image files.",
        extendedDesc: "PDF remains the dominant format for official documents, reports, and multi-page publications, but sharing a single page as an image — for a social media post, email preview, website thumbnail, or design project — requires converting PDF content to a raster image first. PixlTools extracts the first page of any standard PDF and renders it to a high-quality JPEG at 150 DPI, suitable for web display, email, and social sharing. The PDF is rendered server-side using a high-fidelity renderer that accurately interprets fonts, vector graphics, embedded images, and complex page layouts. No software installation is required — the tool works entirely in the browser and produces a clean, sharp image of your PDF page in seconds.",
        category: "utilities",
        apiEndpoint: "/api/pdf-to-image",
        icon: "📑",
        metaTitle: "PDF to JPG Free Online – Extract PDF Pages as Images",
        metaDesc: "Convert PDF to JPG online for free. Extract any PDF page as a high-quality image. No software, no signup. Works on any browser.",
        acceptedFormats: ["application/pdf"],
        outputFormat: "jpeg",
        faqs: [
            { question: "What is the output image quality?", answer: "Pages are exported at 150 DPI — ideal for web display and social sharing. For print-quality output, use a 300 DPI desktop tool." },
            { question: "Can I convert password-protected PDFs?", answer: "Password-protected PDFs must be unlocked before uploading. Our tool supports standard unlocked PDF files." },
            { question: "Can I extract multiple pages at once?", answer: "Our online tool converts the first page of the PDF. For multi-page extraction, desktop tools like Adobe Acrobat or the free command-line tool pdftoppm are recommended." },
        ],
    },
    {
        slug: "watermark-image",
        name: "Watermark Image",
        shortDesc: "Add text watermarks to protect your images.",
        extendedDesc: "Watermarking is the most widely used method for establishing ownership of digital photography, artwork, and design work. A visible watermark signals to viewers that the image has an identified owner, serving as a deterrent to casual copying and attribution-stripping. For professional photographers, stock image creators, and commercial designers, watermarking is an essential step before sharing previews publicly. PixlTools adds custom text watermarks to images server-side using Sharp's composite layer system — the text is rendered at high quality and composited onto the image at the position and opacity you choose. Unlike desktop software, no installation is required, and the process completes in seconds. Your images are processed and immediately deleted — never stored or shared.",
        category: "utilities",
        apiEndpoint: "/api/watermark",
        icon: "🔏",
        metaTitle: "Add Watermark to Image Free – Text Watermark Tool",
        metaDesc: "Add custom text watermarks to protect your photos online for free. Choose position, size, and opacity. No signup, no watermarks added by us.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "What text can I use as a watermark?", answer: "Any text — your name, website URL, copyright notice, or brand name (e.g., '© 2026 YourSite.com')." },
            { question: "Will adding a watermark reduce image quality?", answer: "No. The watermark is composited at full image quality. The result is identical in quality to the original." },
            { question: "Can I control the watermark opacity and position?", answer: "Yes — choose from multiple position presets (corners, center) and adjust opacity from 10% to 100%." },
        ],
    },
    {
        slug: "blur-image",
        name: "Blur Image",
        shortDesc: "Apply Gaussian blur effects to images online.",
        extendedDesc: "Gaussian blur is the most versatile and widely used blur algorithm in image processing. Named after the mathematician Carl Friedrich Gauss, it applies a weighted average to each pixel based on its neighbours, producing a smooth, natural-looking softness that mimics the depth-of-field effect of photographic lenses. Practically, blur is used to hide sensitive information — faces, license plates, addresses, ID numbers — before sharing images publicly on social media or in publications. It is also widely used in UI design to create frosted-glass background effects, in photography editing to isolate subjects by blurring backgrounds, and in artistic projects to achieve a cinematic or dreamlike aesthetic. PixlTools applies Gaussian blur server-side using Sharp, which uses a true convolution kernel for mathematically accurate results.",
        category: "utilities",
        apiEndpoint: "/api/blur",
        icon: "🌫️",
        metaTitle: "Blur Image Free – Hide Info or Add Artistic Effect",
        metaDesc: "Blur images online for free. Apply Gaussian blur to hide sensitive info, faces, or license plates — or create a dreamy artistic effect. No signup.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "Can I blur only part of an image?", answer: "Our current tool applies blur to the entire image. For selective blurring (e.g., blurring a face), use a desktop editor like GIMP or Photoshop." },
            { question: "What blur strength should I use?", answer: "A blur radius of 3–5 is subtle for artistic effects. Use 10–20 to effectively hide sensitive information like faces or license plates." },
            { question: "Does blurring reduce file size?", answer: "Yes — blurred images compress more efficiently because they have less high-frequency detail, resulting in smaller file sizes." },
        ],
    },
    {
        slug: "image-color-picker",
        name: "Image Color Picker",
        shortDesc: "Extract dominant colors and color palette from any image.",
        extendedDesc: "Every great design starts with the right color palette. Whether you're building a brand identity, matching UI colors to a product photo, or reverse-engineering a competitor's color scheme, the Image Color Picker extracts the dominant colors from any image and delivers them as ready-to-use HEX codes and RGB values. Upload a logo to get your brand colors, upload a photograph to build a moodboard palette, or upload a screenshot to identify exact CSS colors used in a design. PixlTools processes the image server-side using perceptual color clustering — not random pixel sampling — so the extracted palette accurately represents the visual impression of the image rather than rare edge-case colors. Results are instant, copyable, and require no signup.",
        category: "utilities",
        apiEndpoint: "/api/color-picker",
        icon: "🎨",
        metaTitle: "Image Color Picker Free – Extract Color Palette & HEX",
        metaDesc: "Pick and extract colors from any image online for free. Get dominant colors, hex codes, and RGB values instantly. No signup, no watermarks.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        howToSteps: [
            { name: "Upload Your Image", text: "Upload any JPG, PNG, or WebP image. Works with photos, logos, screenshots, and artwork." },
            { name: "Extract Colors", text: "Click Process. PixlTools analyzes the image and extracts the most dominant colors using perceptual clustering." },
            { name: "Copy HEX or RGB Values", text: "Copy any color's HEX code or RGB value with one click to use directly in CSS, Figma, Photoshop, or any design tool." },
        ],
        faqs: [
            { question: "How many colors does the color picker extract?", answer: "The tool extracts the top dominant colors from your image, giving you hex codes, RGB values, and a visual palette." },
            { question: "What color formats are shown?", answer: "Results include HEX codes (e.g., #5B21B6) and RGB values (e.g., rgb(91, 33, 182)) for easy use in design tools and CSS." },
            { question: "Can I use this to find brand colors from a logo?", answer: "Yes — upload your logo image and the tool will extract the dominant brand colors with their hex codes." },
        ],
    },
    {
        slug: "image-metadata-viewer",
        name: "Image Metadata Viewer",
        shortDesc: "View EXIF data, camera info, GPS, and image metadata.",
        extendedDesc: "Every photo taken with a modern camera or smartphone contains hidden metadata — a rich record of exactly how and where the photo was captured. EXIF (Exchangeable Image File Format) data includes the camera make and model, lens type, shutter speed, aperture (f-stop), ISO sensitivity, focal length, white balance, and GPS coordinates. This data is embedded invisibly into your image file and is readable by any EXIF-aware software. PixlTools' Image Metadata Viewer reads EXIF data server-side and presents it in a clean, readable format — no installation required. Common uses include verifying photo authenticity, finding GPS coordinates of where a photo was taken, troubleshooting camera settings from old shots, and checking whether sensitive location data is embedded before sharing images publicly.",
        category: "utilities",
        apiEndpoint: "/api/metadata",
        icon: "🔍",
        metaTitle: "EXIF Viewer Free – View Image Metadata Online",
        metaDesc: "View image EXIF metadata online for free. See camera model, shutter speed, GPS location, date taken, and more. No signup, instant results.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp", "image/tiff"],
        howToSteps: [
            { name: "Upload Your Image", text: "Upload your JPG, PNG, WebP, or TIFF image. JPEG files from cameras typically contain the richest EXIF data." },
            { name: "View Metadata", text: "PixlTools extracts and displays all embedded EXIF data including camera model, GPS location, shutter speed, aperture, ISO, and more." },
            { name: "Review & Share", text: "Read through the metadata fields. If you find sensitive GPS data you want to remove before sharing, use an EXIF-stripping tool to clean the file." },
        ],
        faqs: [
            { question: "What metadata does the viewer show?", answer: "It displays camera model, lens info, shutter speed, aperture, ISO, GPS coordinates, date and time taken, and other embedded EXIF data." },
            { question: "Do all images have EXIF data?", answer: "JPEG images from cameras and smartphones typically contain rich EXIF data. PNG and WebP images may have minimal or no metadata." },
            { question: "Does viewing metadata modify my image?", answer: "No. This is a read-only tool — it extracts and displays information without changing your file in any way." },
        ],
    },
    {
        slug: "remove-image-background",
        name: "Background Remover",
        shortDesc: "Remove background from images automatically.",
        extendedDesc: "AI background removal has transformed what was once a time-consuming Photoshop task into a one-click operation. PixlTools uses a server-side AI model trained on millions of images to detect and segment the main subject from its background — handling complex edges like hair, fur, glasses, and fine details. The output is always a transparent PNG file, ready to be placed on any new background, used in an e-commerce listing, added to a presentation, or layered into a design project. No payment, no account, and no Photoshop license required.",
        category: "advanced",
        apiEndpoint: "/api/background-remove",
        icon: "🪄",
        metaTitle: "Remove Background Free – AI Cutout in Seconds",
        metaDesc: "Remove image backgrounds with AI in one click. Get a crisp transparent PNG instantly. 100% free, no signup, no watermarks. Works on photos & products.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        outputFormat: "png",
        isPopular: true,
        howToSteps: [
            { name: "Upload Your Image", text: "Click or drag and drop your JPG, PNG, or WebP photo (up to 10 MB). Works best with clear contrast between the subject and background." },
            { name: "AI Removes the Background", text: "Our AI automatically detects and removes the background from your image. Processing takes just a few seconds." },
            { name: "Download Transparent PNG", text: "Download your result as a transparent PNG, ready to place on any background or use in your designs." },
        ],
        faqs: [
            { question: "What types of images work best?", answer: "Images with a clear contrast between the subject and background work best — people against plain walls, products on tables, logos on solid backgrounds." },
            { question: "Does it work on hair and fine details?", answer: "Yes — our AI handles hair, fur, and fine edges well when the original photo has good contrast and lighting." },
            { question: "What is the output format?", answer: "The result is always a transparent PNG file, perfect for overlaying on new backgrounds or using in design projects." },
            { question: "Is AI background removal free?", answer: "Yes — background removal is completely free on PixlTools with no account, no subscription, and no watermarks." },
        ],
    },
    {
        slug: "image-upscaler",
        name: "Image Upscaler",
        shortDesc: "Increase image resolution without losing quality.",
        extendedDesc: "Traditional image upscaling (bicubic or bilinear interpolation) simply stretches existing pixels, creating a blurry result. AI upscaling works fundamentally differently — it analyzes patterns in the image and synthesizes new pixel detail that is plausible given the surrounding context. This produces sharper edges, clearer text, and more realistic textures at 2x and 4x the original resolution. PixlTools' upscaler is ideal for enlarging old photos, preparing low-resolution product images for print, or recovering detail from compressed screenshots.",
        category: "advanced",
        apiEndpoint: "/api/upscale",
        icon: "🔭",
        metaTitle: "AI Image Upscaler Free – Enlarge Up to 4x, No Blur",
        metaDesc: "Upscale images 2x, 3x, or 4x without blurring using AI. Enlarge photos, product images & artwork for free. No account needed, instant results.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        howToSteps: [
            { name: "Upload Your Image", text: "Upload your JPG, PNG, or WebP image (up to 10 MB). Works best when starting from the highest quality original available." },
            { name: "Choose Upscale Factor", text: "Select 2x, 3x, or 4x. For best results, choose 2x — AI results are sharpest at this scale." },
            { name: "Download Upscaled Image", text: "Click Process and then Download to save your high-resolution upscaled image." },
        ],
        faqs: [
            { question: "How does AI upscaling work?", answer: "AI upscaling uses neural networks (Super-Resolution) trained on millions of images to predict and add realistic detail when enlarging. Results are sharper than traditional bicubic scaling." },
            { question: "Can upscaling make a blurry photo sharp?", answer: "It can improve clarity and add detail, but cannot fully recover a severely blurry or out-of-focus photo. Start with the sharpest original you have." },
            { question: "What upscale factor should I use?", answer: "2x gives excellent results on most images. 4x is best for simple subjects like portraits — very detailed textures can show some softening at 4x." },
            { question: "Does upscaling increase file size?", answer: "Yes — a 2x upscale quadruples the pixel count, increasing file size significantly. Use our Image Compressor afterwards if you need a smaller file." },
        ],
    },
    {
        slug: "image-grayscale",
        name: "Grayscale Converter",
        shortDesc: "Convert color images to black and white grayscale.",
        extendedDesc: "Grayscale conversion is one of the most powerful and timeless aesthetic choices in photography and design. Removing colour information draws the viewer's eye to composition, light, shadow, and texture — aspects that colour can sometimes distract from. Classic black-and-white photography remains among the most highly regarded aesthetic in portraiture, landscape, and documentary photography. In design, grayscale images integrate seamlessly into monochrome layouts and brand guidelines, and are frequently used for backgrounds, hero images, and card thumbnails where colour consistency is important. PixlTools converts images to grayscale server-side using Sharp's luminance calculation, which weights the red, green, and blue channels (using the industry-standard ITU-R BT.709 coefficients) to produce a perceptually accurate tonal representation — not a flat average that would give muddy, inaccurate results.",
        category: "advanced",
        apiEndpoint: "/api/grayscale",
        icon: "⬛",
        metaTitle: "Grayscale Converter Free – Color Photo to Black & White",
        metaDesc: "Convert images to black and white grayscale online for free. Perfect for photography, design, and artistic effects. Instant download, no signup.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "What does grayscale conversion do?", answer: "Grayscale conversion removes all color information from an image, replacing each pixel with a shade of gray that represents its luminance (brightness)." },
            { question: "Is grayscale the same as black and white?", answer: "Grayscale images contain all shades from pure black to pure white, making them true black-and-white images with full tonal range." },
            { question: "Can I convert back from grayscale to color?", answer: "No — once color information is removed, it cannot be recovered. Always keep a copy of the original color image." },
        ],
    },
    {
        slug: "image-brightness",
        name: "Brightness Adjuster",
        shortDesc: "Adjust image brightness levels online.",
        extendedDesc: "Brightness is the most fundamental parameter in photography and digital imaging — it determines how light or dark the overall image appears by scaling the luminance of every pixel. Adjusting brightness is the first step in correcting exposure errors from shooting in automatic mode, recovering detail from underexposed photos taken in low light, or deliberately darkening overexposed outdoor shots. Unlike Photoshop's complex curves and levels controls, PixlTools provides a simple, effective brightness multiplier applied uniformly to all channels. This is ideal for quick correction tasks where you need to fix an image before sharing it online without opening a full editing suite. The adjustment is applied server-side using Sharp, producing clean, artifact-free results even at significant brightness adjustments.",
        category: "advanced",
        apiEndpoint: "/api/brightness",
        icon: "☀️",
        metaTitle: "Adjust Image Brightness Free – Lighten or Darken Photos",
        metaDesc: "Adjust image brightness online for free. Lighten underexposed or darken overexposed photos with a simple slider. No signup, instant results.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "How much can I adjust brightness?", answer: "You can brighten or darken an image across a wide range. Moving the slider too far in either direction will clip highlights or shadows." },
            { question: "Does adjusting brightness affect image quality?", answer: "Moderate brightness adjustments have minimal impact on quality. Extreme adjustments can cause clipping (pure white or pure black areas losing detail)." },
            { question: "Can I undo a brightness adjustment?", answer: "Re-upload your original image to start fresh. We recommend keeping an unedited copy of your original." },
        ],
    },
    {
        slug: "image-contrast",
        name: "Contrast Adjuster",
        shortDesc: "Enhance or reduce image contrast for better visuals.",
        extendedDesc: "Contrast is one of the most powerful tools in photography and design — it controls how much the light and dark areas of an image differ from each other. High contrast makes images feel punchy, dramatic, and bold, which is ideal for advertising visuals, editorial photography, and social media content. Low contrast creates a soft, hazy, film-like aesthetic popular in portrait photography and matte editing styles. PixlTools' contrast adjuster uses Sharp's linear contrast algorithm, which applies a mathematically precise multiplier to each pixel's luminance channel — unlike browser-based tools that use approximations. This produces clean, artifact-free results across all image types. The tool works equally well for correcting underexposed flat images (boost contrast) and creating stylised low-contrast looks for artistic projects.",
        category: "advanced",
        apiEndpoint: "/api/contrast",
        icon: "🌗",
        metaTitle: "Adjust Image Contrast Free – Enhance Photo Quality",
        metaDesc: "Adjust image contrast online for free. Boost contrast to make colors pop or reduce it for a softer look. No account needed, instant download.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        howToSteps: [
            { name: "Upload Your Image", text: "Upload your JPG, PNG, or WebP image. The preview will update as you adjust the contrast setting." },
            { name: "Adjust Contrast", text: "Move the slider right to increase contrast (punchier, more vivid) or left to decrease it (softer, more muted). Start with small adjustments for natural results." },
            { name: "Download", text: "Click Process then Download to save your contrast-adjusted image. No watermarks, no account required." },
        ],
        faqs: [
            { question: "What does increasing contrast do?", answer: "Increasing contrast makes dark areas darker and bright areas brighter, making the image appear more vivid and defined." },
            { question: "When would I reduce contrast?", answer: "Reducing contrast creates a softer, more muted aesthetic — popular in film photography edits and matte photo styles." },
            { question: "Should I adjust brightness or contrast first?", answer: "Adjust brightness first to achieve the correct exposure, then use contrast to add punch or softness to the image." },
        ],
    },
    {
        slug: "image-sharpen",
        name: "Image Sharpen Tool",
        shortDesc: "Sharpen blurry or soft images for crisp details.",
        extendedDesc: "Image sharpening enhances the perceived detail in a photo by increasing edge contrast — the difference in pixel values across boundaries between different areas of the image. This makes fine textures, hair strands, text, and architectural details appear crisper and more defined. PixlTools uses an unsharp mask algorithm (the industry standard used in Photoshop, Lightroom, and Sharp itself), which works by subtracting a blurred version of the image from itself to detect edges and then amplifies them. The key parameters are sigma (the radius of edge detection) and the strength (how aggressively edges are amplified). PixlTools applies a balanced, professionally tuned default that works well for most photographs — sharp enough to visibly improve clarity without introducing the halo artifacts that plague over-sharpened images.",
        category: "advanced",
        apiEndpoint: "/api/sharpen",
        icon: "💎",
        metaTitle: "Sharpen Image Free – Crisp Details in Seconds",
        metaDesc: "Sharpen blurry or soft images online for free. Make photo details crisper and more defined with one click. No signup, instant download.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        howToSteps: [
            { name: "Upload Your Image", text: "Upload your JPG, PNG, or WebP image. Sharpening works best on slightly soft images — it cannot recover severely blurry or out-of-focus shots." },
            { name: "Apply Sharpening", text: "Click Process. PixlTools applies a professional unsharp mask to enhance edge contrast and bring out fine detail across the image." },
            { name: "Download Sharpened Image", text: "Download your sharper image instantly. Sharpening is ideal as the final step — apply it after resizing, brightness, or contrast adjustments." },
        ],
        faqs: [
            { question: "Can sharpening fix a blurry photo?", answer: "Sharpening enhances edge definition and brings out detail in slightly soft images. It cannot fully recover severely blurry or out-of-focus photos." },
            { question: "How much sharpening should I apply?", answer: "Moderate sharpening works best — over-sharpening creates a halo effect around edges and can make images look artificial." },
            { question: "When should I sharpen an image?", answer: "Apply sharpening as the final editing step, after resizing and other adjustments. Sharpening is also recommended after upscaling to restore crispness." },
        ],
    },
    {
        slug: "image-thumbnail",
        name: "Thumbnail Generator",
        shortDesc: "Generate optimized thumbnails for YouTube, blogs, and more.",
        extendedDesc: "Thumbnails are the single most important factor in click-through rate on platforms like YouTube, Pinterest, and blog post grids — they are the first visual impression that determines whether a viewer clicks or scrolls past. YouTube displays thumbnails at 320×180px in search results but requires the source file to be at least 1280×720px to appear sharp on high-resolution displays. PixlTools generates thumbnails that meet the exact pixel requirements for each major platform: YouTube (1280×720), Instagram (1080×1080), Twitter/X (1600×900), and LinkedIn (1200×627). The output is a perfectly sized, Sharp-optimised image ready for immediate upload — no cropping, no guesswork, and no watermarks. Processing happens server-side in under a second.",
        category: "advanced",
        apiEndpoint: "/api/thumbnail",
        icon: "🖼️",
        metaTitle: "Thumbnail Generator Free – YouTube, Blog & Social Media",
        metaDesc: "Generate optimized thumbnails for YouTube (1280×720), blogs, and social media online for free. No signup, instant download, no watermarks.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "What size thumbnail does YouTube require?", answer: "YouTube thumbnails should be 1280×720px (16:9 aspect ratio) at a minimum. Our tool generates thumbnails at the exact right dimensions." },
            { question: "What sizes can I generate?", answer: "You can generate thumbnails for YouTube (1280×720), Instagram (1080×1080), Twitter (1600×900), LinkedIn (1200×627), and custom sizes." },
            { question: "Will my thumbnail have watermarks?", answer: "No. All PixlTools outputs are 100% watermark-free." },
        ],
    },
    {
        slug: "image-border",
        name: "Image Border Adder",
        shortDesc: "Add custom colored borders and frames to images.",
        extendedDesc: "Adding a border to an image is a simple but powerful visual technique — it frames the subject, creates separation between the image and the background, and adds a polished, finished look to photos shared on social media or embedded in documents. White borders give photos a clean, printed-photograph aesthetic popular on Instagram. Black borders create a dramatic, cinematic effect. Coloured borders can reinforce brand identity when sharing product or portfolio images. PixlTools' border tool lets you specify the exact border width in pixels and choose any RGB color via a full color picker. The border is added as an extension of the canvas — your original image content is never cropped or altered. The output dimensions increase by twice the border width on each side, and the result is available as JPG or PNG.",
        category: "advanced",
        apiEndpoint: "/api/border",
        icon: "🖼️",
        metaTitle: "Add Border to Image Free – Custom Color & Size",
        metaDesc: "Add custom borders and frames to images online for free. Choose border size, color, and style instantly. No signup, no watermarks.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        howToSteps: [
            { name: "Upload Your Image", text: "Upload your JPG, PNG, or WebP image. PNG files with transparency are supported — the border will be added outside the transparent area." },
            { name: "Set Border Options", text: "Choose your border width in pixels (e.g., 20px for a subtle frame, 60px for a bold border) and select any color using the color picker." },
            { name: "Download Your Framed Image", text: "Click Process then Download. Your bordered image is ready instantly with no watermarks. No account required." },
        ],
        faqs: [
            { question: "Can I choose any border color?", answer: "Yes — use the color picker to select any RGB color for your border, including white, black, or any custom brand color." },
            { question: "Will adding a border increase the image file size?", answer: "Slightly — adding a border increases the canvas dimensions, which adds a small amount to the file size." },
            { question: "Can I add a border to a PNG with transparency?", answer: "Yes. PNG transparency is preserved when adding borders, and the border pixels will be fully opaque in your chosen color." },
        ],
    },
    {
        slug: "image-aspect-ratio",
        name: "Aspect Ratio Changer",
        shortDesc: "Change image aspect ratio to 16:9, 4:3, 1:1, and more.",
        extendedDesc: "Aspect ratio is the proportional relationship between an image's width and height, expressed as two numbers separated by a colon (e.g. 16:9). Different platforms and devices have strict expectations about aspect ratio: YouTube requires 16:9 for video thumbnails, Instagram posts perform best at 4:5 (portrait) or 1:1 (square), Stories and Reels must be 9:16, and print photos traditionally use 4:3 or 3:2. Uploading an image at the wrong aspect ratio causes platforms to crop or letterbox it automatically — often cutting off the most important part of the composition. PixlTools changes aspect ratios correctly by cropping to the specified ratio, always centring the crop to preserve the visual centre of the image. The result is a properly formatted image that uploads cleanly to any platform without automatic cropping surprises.",
        category: "advanced",
        apiEndpoint: "/api/resize",
        icon: "📺",
        metaTitle: "Change Aspect Ratio Free – 16:9, 4:3, 1:1 & More",
        metaDesc: "Change image aspect ratio online for free. Resize to 16:9, 4:3, 1:1, 9:16, or any custom ratio. No signup, instant download.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "What aspect ratios can I set?", answer: "Presets include 16:9 (widescreen), 4:3 (standard), 1:1 (square), 9:16 (portrait/mobile), and 21:9 (cinematic). You can also enter custom ratios." },
            { question: "Will changing aspect ratio crop my image?", answer: "Yes — changing the aspect ratio requires either cropping the image or adding padding (letterboxing) to fit the new ratio without distortion." },
            { question: "What is the best aspect ratio for Instagram?", answer: "1:1 (square) at 1080×1080px for posts, 4:5 (portrait) at 1080×1350px for maximum display size, and 9:16 at 1080×1920px for Stories and Reels." },
        ],
    },
    {
        slug: "reduce-image-file-size",
        name: "Image File Size Reducer",
        shortDesc: "Reduce image file size for email, web, and uploads.",
        extendedDesc: "Many real-world situations demand an image under a specific file size threshold — government portals require passport photos under 100KB, email providers have attachment limits around 10–25MB, social platforms silently recompress oversized uploads, and employment sites often cap CVs and portfolios at 2MB. Unlike generic compressors, PixlTools targets the root causes of large file size: unnecessarily high resolution and insufficient compression. The correct workflow is always to resize to the display dimensions first (removing surplus pixels that add no visual value), then compress to the quality level appropriate for the use case — typically 75–80 for web, 85–90 for print preview. Our file size reducer applies both steps in the correct order, server-side, for consistent and reproducible results.",
        category: "advanced",
        apiEndpoint: "/api/compress",
        icon: "📦",
        metaTitle: "Reduce Image File Size Free – Compress Photos Online",
        metaDesc: "Reduce image file size for email, social media & websites online for free. Compress photos to under 100KB, 200KB, or 500KB. No signup.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        faqs: [
            { question: "How do I reduce an image to under 100KB?", answer: "Resize to 800×600px first, then compress at quality 70–75. This typically results in files of 50–100KB for most photos." },
            { question: "What's the best way to reduce file size for email?", answer: "Keep dimensions below 1200px wide and compress to quality 80. Most email-ready photos should be 200–500KB." },
            { question: "Should I resize or compress first?", answer: "Always resize first to remove unnecessary pixels, then compress. Compressing a large image gives worse results than compressing a correctly-sized image." },
        ],
    },
    {
        slug: "image-to-base64",
        name: "Image to Base64",
        shortDesc: "Convert any image to a Base64 data URL for web embedding.",
        extendedDesc: "Base64 encoding converts binary image data into a plain-text ASCII string that can be embedded directly inside HTML, CSS, JSON, or XML files — eliminating the need for a separate HTTP request to fetch an external image file. This is particularly useful for embedding small icons, logos, and UI elements in single-file HTML emails (which often block external image requests), inline SVG files, CSS background-image properties, and REST API payloads that need to carry image data without multipart form encoding. PixlTools converts your image server-side to a complete, ready-to-use data URL in the format `data:image/jpeg;base64,...`. The output can be pasted directly into an `<img src>` attribute, a CSS `url()` value, or a JSON string field. For images larger than 10–20KB, Base64 inflates file size by ~33%, so this format is best reserved for small assets.",
        category: "utilities",
        apiEndpoint: "/api/image-to-base64",
        icon: "💻",
        metaTitle: "Image to Base64 Free – Encode for HTML, CSS & JSON",
        metaDesc: "Convert images to Base64 data URLs online for free. Embed images directly in HTML, CSS, or JSON without external files. No signup, instant copy.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        isNew: true,
        howToSteps: [
            { name: "Upload Your Image", text: "Upload your JPG, PNG, or WebP image. For best results, use small images (icons, logos, UI elements) under 50KB." },
            { name: "Generate Base64 String", text: "Click Process. PixlTools encodes your image into a complete Base64 data URL string ready to paste into HTML, CSS, or JSON." },
            { name: "Copy & Use", text: "Click Copy to clipboard. Use the data URL as an `<img src>`, CSS `url()`, or JSON value — no external file needed." },
        ],
        faqs: [
            { question: "What is Base64 encoding for images?", answer: "Base64 converts binary image data into a text string that can be embedded directly in HTML, CSS, or JSON files — eliminating an additional HTTP request." },
            { question: "When should I use Base64 for images?", answer: "Use Base64 for small images like icons and logos where the overhead of an HTTP request outweighs the base64 size increase (~33%). Avoid it for large photos." },
            { question: "How do I embed the Base64 image in HTML?", answer: "Use it as the src attribute: <img src=\"data:image/png;base64,YOUR_BASE64_STRING\" />. Our tool provides the complete ready-to-use data URL." },
        ],
    },
    {
        slug: "svg-to-png",
        name: "SVG to PNG",
        shortDesc: "Convert SVG vector graphics to PNG images online.",
        extendedDesc: "SVG (Scalable Vector Graphics) is the ideal format for logos, icons, and illustrations because it scales to any size without losing quality. However, SVG is not universally supported — email clients block SVG, many CMSs don't accept it for uploads, social media platforms reject it, and some apps require raster images. Converting SVG to PNG gives you a pixel-perfect, universally compatible raster version of your vector graphic at whatever resolution you need. PixlTools renders SVG files server-side using a high-fidelity SVG renderer — meaning complex gradients, filters, text, and shapes are rendered accurately at the specified output resolution. For Retina/HiDPI displays, export at 2x your intended display size (e.g., export at 400×400px for a 200×200px display slot).",
        category: "conversion",
        apiEndpoint: "/api/svg-to-png",
        icon: "🎨",
        metaTitle: "SVG to PNG Free – High-Quality Vector to Raster",
        metaDesc: "Convert SVG files to PNG online for free. High-quality vector to raster conversion at any resolution. No signup, no watermarks, instant download.",
        acceptedFormats: ["image/svg+xml"],
        outputFormat: "png",
        isNew: true,
        howToSteps: [
            { name: "Upload Your SVG", text: "Upload your SVG file. PixlTools supports all standard SVG features including gradients, filters, text, and complex paths." },
            { name: "Set Output Resolution", text: "Choose your target PNG dimensions. For Retina displays, use 2× your intended display size. For print, target 300 DPI at the print dimensions." },
            { name: "Download PNG", text: "Click Process then Download. Your SVG is rendered to a high-quality PNG — with full transparency preserved — ready to use anywhere." },
        ],
        faqs: [
            { question: "Why convert SVG to PNG?", answer: "PNG files work everywhere — in emails, presentations, and apps that don't support SVG. Converting creates a fixed-resolution raster copy of your vector graphic." },
            { question: "At what resolution is the PNG exported?", answer: "You can specify the output resolution. Higher values produce sharper PNGs suitable for print, while lower values are better for web use." },
            { question: "Will transparency be preserved?", answer: "Yes — PNG supports full alpha transparency. Transparent areas in your SVG will remain transparent in the output PNG." },
        ],
    },
    {
        slug: "heic-to-jpg",
        name: "HEIC to JPG",
        shortDesc: "Convert iPhone HEIC/HEIF photos to JPEG instantly.",
        extendedDesc: "Apple introduced HEIC (High Efficiency Image Container, based on the HEIF standard) as the default photo format for iPhones from iOS 11 onwards. HEIC files achieve roughly twice the compression of JPEG at equivalent visual quality — a major advantage for device storage — but they are not supported by Windows without additional codec packs, are rejected by most web upload forms, and cannot be opened by the majority of editing and sharing tools outside the Apple ecosystem. Converting HEIC to JPEG resolves every compatibility issue instantly: the resulting JPG file opens in every Windows application, uploads to every website, attaches to any email, and is accepted by every photo editing programme. PixlTools decodes HEIC files server-side and re-encodes them as high-quality JPEG, preserving colour accuracy and image detail throughout the conversion.",
        category: "conversion",
        apiEndpoint: "/api/heic-to-jpg",
        icon: "📱",
        metaTitle: "HEIC to JPG Free – Convert iPhone Photos Instantly",
        metaDesc: "Convert iPhone HEIC photos to JPG online for free. No app install, no account needed. Works on any browser — instant conversion, no watermarks.",
        acceptedFormats: ["image/heic", "image/heif"],
        outputFormat: "jpg",
        isNew: true,
        howToSteps: [
            { name: "Upload HEIC Photo", text: "Click or drag and drop your iPhone HEIC or HEIF photo (up to 10 MB). Transfer the file from your iPhone using AirDrop, iCloud, or USB." },
            { name: "Convert to JPG", text: "Click Process. Your HEIC photo is automatically converted to a high-quality JPEG file." },
            { name: "Download JPG", text: "Download your JPG file. It's now compatible with all devices, apps, email clients, and websites." },
        ],
        faqs: [
            { question: "What is a HEIC file?", answer: "HEIC (High Efficiency Image Container) is Apple's default photo format for iPhones since iOS 11. It offers better compression than JPEG but isn't widely supported outside Apple devices." },
            { question: "Why can't I open HEIC photos on my Windows PC?", answer: "Windows doesn't natively support HEIC. Converting to JPG makes the photo universally compatible with all Windows apps and browsers." },
            { question: "Does converting HEIC to JPG reduce quality?", answer: "Minimal quality difference — HEIC and JPEG are both compressed formats. At high quality settings, the conversion is virtually lossless to the human eye." },
            { question: "How do I get HEIC files from my iPhone?", answer: "Transfer files using AirDrop to a Mac (then to this tool), iCloud Drive (accessible from any browser), or USB cable to a computer." },
        ],
    },
    {
        slug: "photo-collage-maker",
        name: "Photo Collage Maker",
        shortDesc: "Combine 2–16 images into a beautiful grid collage.",
        extendedDesc: "A photo collage combines multiple individual images into a single composed image — a format that has become one of the most popular approaches for social media posts, family albums, event recaps, real estate listings, and e-commerce product galleries. Rather than posting multiple separate images, a collage lets you tell a visual story in a single, shareable file. PixlTools' collage maker supports between 2 and 16 photos, automatically calculating an intelligent grid layout based on the number of images selected. Each photo is resized and positioned in its grid cell with consistent spacing, and the final composition is rendered server-side using Sharp at high resolution. The output is available as either a JPG (smaller file size, ideal for sharing) or PNG (no compression artifacts, ideal for printing or further editing). No watermarks are added.",
        category: "utilities",
        apiEndpoint: "/api/collage",
        icon: "🖼️",
        metaTitle: "Photo Collage Maker Free – Combine Up to 16 Images",
        metaDesc: "Make photo collages online for free. Combine up to 16 images into a custom grid layout. No watermarks, no signup. Download as JPG or PNG instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        isNew: true,
        faqs: [
            { question: "How many photos can I combine in one collage?", answer: "You can combine between 2 and 16 photos into a single grid collage. The layout automatically adjusts based on the number of images." },
            { question: "Will my collage have watermarks?", answer: "No — all PixlTools outputs are 100% watermark-free. Your collage belongs to you." },
            { question: "What are the output dimensions of the collage?", answer: "The default output is a high-quality square collage. You can customize grid layout and dimensions. Final output is available as JPG or PNG." },
            { question: "Can I use photos from my phone?", answer: "Yes — PixlTools works on any device. Upload photos directly from your iPhone or Android camera roll using your mobile browser." },
        ],
    },
];

export const TOOL_CATEGORIES = {
    compression: { label: "Image Compression", color: "from-blue-500 to-cyan-500", desc: "Shrink file sizes without sacrificing visual quality" },
    "resize-crop": { label: "Resize & Crop", color: "from-violet-500 to-purple-500", desc: "Change dimensions, crop, rotate, and flip images" },
    conversion: { label: "Image Conversion", color: "from-rose-500 to-pink-500", desc: "Convert between JPEG, PNG, WEBP, and PDF formats" },
    utilities: { label: "Image Utilities", color: "from-amber-500 to-orange-500", desc: "Watermark, blur, color-pick, and inspect image metadata" },
    advanced: { label: "Advanced Tools", color: "from-emerald-500 to-teal-500", desc: "AI background removal, upscaling, filters, and more" },
};

export function getToolBySlug(slug: string): ToolData | undefined {
    return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolData[] {
    return TOOLS.filter((t) => t.category === category);
}
