export type ToolCategory =
    | "compression"
    | "resize-crop"
    | "conversion"
    | "utilities"
    | "advanced";

export interface ToolData {
    slug: string;
    name: string;
    shortDesc: string;
    category: ToolCategory;
    apiEndpoint: string;
    icon: string;
    metaTitle: string;
    metaDesc: string;
    acceptedFormats: string[];
    outputFormat?: string;
    params?: Record<string, string>;
}

export const TOOLS: ToolData[] = [
    {
        slug: "compress-image",
        name: "Compress Image",
        shortDesc: "Reduce image file size while maintaining quality.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "🗜️",
        metaTitle: "Free Image Compressor – Reduce Image Size Online",
        metaDesc: "Compress JPG, PNG, and WEBP images online for free without losing quality. Fast, secure, no signup required.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "compress-jpg",
        name: "Compress JPG",
        shortDesc: "Compress JPEG images to reduce file size instantly.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "📸",
        metaTitle: "Compress JPG Online – Reduce JPEG Size for Free",
        metaDesc: "Compress JPEG images online. Reduce JPG file size up to 80% without visible quality loss.",
        acceptedFormats: ["image/jpeg"],
        params: { format: "jpeg" },
    },
    {
        slug: "compress-png",
        name: "Compress PNG",
        shortDesc: "Compress PNG files without losing transparency.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "🖼️",
        metaTitle: "Compress PNG Online – Reduce PNG File Size Free",
        metaDesc: "Compress PNG images online for free. Preserve transparency while reducing file size significantly.",
        acceptedFormats: ["image/png"],
        params: { format: "png" },
    },
    {
        slug: "compress-webp",
        name: "Compress WEBP",
        shortDesc: "Reduce WEBP image file size with optimal compression.",
        category: "compression",
        apiEndpoint: "/api/compress",
        icon: "⚡",
        metaTitle: "Compress WEBP Online – Reduce WEBP File Size Free",
        metaDesc: "Compress WEBP images for free. Achieve smaller file sizes with minimal quality reduction.",
        acceptedFormats: ["image/webp"],
        params: { format: "webp" },
    },
    {
        slug: "resize-image",
        name: "Resize Image",
        shortDesc: "Resize images to any dimension in pixels or percentage.",
        category: "resize-crop",
        apiEndpoint: "/api/resize",
        icon: "📐",
        metaTitle: "Resize Image Online – Change Image Dimensions Free",
        metaDesc: "Resize images online for free. Change width, height, or scale percentage instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "crop-image",
        name: "Crop Image",
        shortDesc: "Crop images to a specific area or aspect ratio.",
        category: "resize-crop",
        apiEndpoint: "/api/crop",
        icon: "✂️",
        metaTitle: "Crop Image Online Free – Cut Image to Any Size",
        metaDesc: "Crop images online for free. Select any area, set custom dimensions, or choose a preset aspect ratio.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "rotate-image",
        name: "Rotate Image",
        shortDesc: "Rotate images 90°, 180°, or any custom angle.",
        category: "resize-crop",
        apiEndpoint: "/api/rotate",
        icon: "🔄",
        metaTitle: "Rotate Image Online Free – Rotate Photo Any Angle",
        metaDesc: "Rotate images online for free. Rotate 90°, 180°, 270° or enter a custom angle instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "flip-image",
        name: "Flip Image",
        shortDesc: "Flip images horizontally or vertically online.",
        category: "resize-crop",
        apiEndpoint: "/api/flip",
        icon: "🔀",
        metaTitle: "Flip Image Online Free – Mirror Image Horizontally or Vertically",
        metaDesc: "Flip or mirror images online for free. Flip horizontally or vertically in one click.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "jpg-to-png",
        name: "JPG to PNG",
        shortDesc: "Convert JPEG images to PNG format with transparency support.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "JPG to PNG Converter – Convert JPEG to PNG Free Online",
        metaDesc: "Convert JPG to PNG online for free. Instantly convert JPEG images to PNG with transparency support.",
        acceptedFormats: ["image/jpeg"],
        outputFormat: "png",
        params: { to: "png" },
    },
    {
        slug: "png-to-jpg",
        name: "PNG to JPG",
        shortDesc: "Convert PNG images to JPEG format for smaller file sizes.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "PNG to JPG Converter – Convert PNG to JPEG Free Online",
        metaDesc: "Convert PNG to JPG online for free. Reduce file size by converting PNG images to JPEG format.",
        acceptedFormats: ["image/png"],
        outputFormat: "jpeg",
        params: { to: "jpeg" },
    },
    {
        slug: "jpg-to-webp",
        name: "JPG to WEBP",
        shortDesc: "Convert JPEG images to modern WEBP format.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "JPG to WEBP Converter – Convert JPEG to WEBP Free",
        metaDesc: "Convert JPG to WEBP online for free. Modern WEBP format offers 30% smaller sizes than JPEG.",
        acceptedFormats: ["image/jpeg"],
        outputFormat: "webp",
        params: { to: "webp" },
    },
    {
        slug: "webp-to-jpg",
        name: "WEBP to JPG",
        shortDesc: "Convert WEBP images to universally supported JPEG.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "WEBP to JPG Converter – Convert WEBP to JPEG Free Online",
        metaDesc: "Convert WEBP to JPG online for free. Make WEBP images compatible with all devices and apps.",
        acceptedFormats: ["image/webp"],
        outputFormat: "jpeg",
        params: { to: "jpeg" },
    },
    {
        slug: "png-to-webp",
        name: "PNG to WEBP",
        shortDesc: "Convert PNG images to WEBP for better web performance.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "PNG to WEBP Converter – Convert PNG to WEBP Free Online",
        metaDesc: "Convert PNG to WEBP online for free. Smaller file sizes with better quality for the web.",
        acceptedFormats: ["image/png"],
        outputFormat: "webp",
        params: { to: "webp" },
    },
    {
        slug: "webp-to-png",
        name: "WEBP to PNG",
        shortDesc: "Convert WEBP images to PNG format with lossless output.",
        category: "conversion",
        apiEndpoint: "/api/convert",
        icon: "🔃",
        metaTitle: "WEBP to PNG Converter – Convert WEBP to PNG Free Online",
        metaDesc: "Convert WEBP to PNG online for free. Lossless output with full transparency support.",
        acceptedFormats: ["image/webp"],
        outputFormat: "png",
        params: { to: "png" },
    },
    {
        slug: "image-to-pdf",
        name: "Image to PDF",
        shortDesc: "Convert JPG, PNG, or WEBP images to PDF documents.",
        category: "utilities",
        apiEndpoint: "/api/image-to-pdf",
        icon: "📄",
        metaTitle: "Image to PDF Converter – Convert Images to PDF Free Online",
        metaDesc: "Convert images to PDF online for free. Turn JPG, PNG, or WEBP into a PDF document instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        outputFormat: "pdf",
    },
    {
        slug: "pdf-to-image",
        name: "PDF to Image",
        shortDesc: "Extract PDF pages and convert them to image files.",
        category: "utilities",
        apiEndpoint: "/api/pdf-to-image",
        icon: "📑",
        metaTitle: "PDF to Image Converter – Convert PDF to JPG Free Online",
        metaDesc: "Convert PDF to image online for free. Extract PDF pages as JPG or PNG images instantly.",
        acceptedFormats: ["application/pdf"],
        outputFormat: "jpeg",
    },
    {
        slug: "watermark-image",
        name: "Watermark Image",
        shortDesc: "Add text watermarks to protect your images.",
        category: "utilities",
        apiEndpoint: "/api/watermark",
        icon: "🔏",
        metaTitle: "Add Watermark to Image Online Free – Text Watermark Tool",
        metaDesc: "Add text watermarks to images online for free. Protect your photos with custom watermarks.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "blur-image",
        name: "Blur Image",
        shortDesc: "Apply Gaussian blur effects to images online.",
        category: "utilities",
        apiEndpoint: "/api/blur",
        icon: "🌫️",
        metaTitle: "Blur Image Online Free – Apply Blur Effect to Photos",
        metaDesc: "Blur images online for free. Apply Gaussian blur to hide sensitive info or create artistic effects.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-color-picker",
        name: "Image Color Picker",
        shortDesc: "Extract dominant colors and color palette from any image.",
        category: "utilities",
        apiEndpoint: "/api/color-picker",
        icon: "🎨",
        metaTitle: "Image Color Picker – Extract Colors from Image Online Free",
        metaDesc: "Pick colors from any image online for free. Extract dominant colors and hex codes instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-metadata-viewer",
        name: "Image Metadata Viewer",
        shortDesc: "View EXIF data, camera info, GPS, and image metadata.",
        category: "utilities",
        apiEndpoint: "/api/metadata",
        icon: "🔍",
        metaTitle: "Image Metadata Viewer – View EXIF Data Online Free",
        metaDesc: "View image metadata and EXIF data online for free. See camera settings, GPS, date, and more.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp", "image/tiff"],
    },
    {
        slug: "remove-image-background",
        name: "Background Remover",
        shortDesc: "Remove background from images automatically.",
        category: "advanced",
        apiEndpoint: "/api/background-remove",
        icon: "🪄",
        metaTitle: "Remove Image Background Free Online – Background Remover Tool",
        metaDesc: "Remove image background online for free. Automatic background removal for photos and graphics.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
        outputFormat: "png",
    },
    {
        slug: "image-upscaler",
        name: "Image Upscaler",
        shortDesc: "Increase image resolution without losing quality.",
        category: "advanced",
        apiEndpoint: "/api/upscale",
        icon: "🔭",
        metaTitle: "Image Upscaler Online Free – Increase Image Resolution",
        metaDesc: "Upscale images online for free. Increase image resolution up to 4x without losing quality.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-grayscale",
        name: "Grayscale Converter",
        shortDesc: "Convert color images to black and white grayscale.",
        category: "advanced",
        apiEndpoint: "/api/grayscale",
        icon: "⬛",
        metaTitle: "Image Grayscale Converter – Convert Photo to Black & White Free",
        metaDesc: "Convert images to grayscale online for free. Turn color photos into black and white instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-brightness",
        name: "Brightness Adjuster",
        shortDesc: "Adjust image brightness levels online.",
        category: "advanced",
        apiEndpoint: "/api/brightness",
        icon: "☀️",
        metaTitle: "Adjust Image Brightness Online Free – Photo Brightness Tool",
        metaDesc: "Adjust image brightness online for free. Lighten or darken photos with a simple slider.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-contrast",
        name: "Contrast Adjuster",
        shortDesc: "Enhance or reduce image contrast for better visuals.",
        category: "advanced",
        apiEndpoint: "/api/contrast",
        icon: "🌗",
        metaTitle: "Adjust Image Contrast Online Free – Photo Contrast Tool",
        metaDesc: "Adjust image contrast online for free. Improve photo quality by boosting or reducing contrast.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-sharpen",
        name: "Image Sharpen Tool",
        shortDesc: "Sharpen blurry or soft images for crisp details.",
        category: "advanced",
        apiEndpoint: "/api/sharpen",
        icon: "💎",
        metaTitle: "Sharpen Image Online Free – Make Blurry Photos Clear",
        metaDesc: "Sharpen images online for free. Fix blurry photos and make details crisper instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-thumbnail",
        name: "Thumbnail Generator",
        shortDesc: "Generate optimized thumbnails for YouTube, blogs, and more.",
        category: "advanced",
        apiEndpoint: "/api/thumbnail",
        icon: "🖼️",
        metaTitle: "Thumbnail Generator Online Free – Create Image Thumbnails",
        metaDesc: "Generate image thumbnails online for free. Create optimized thumbnails for YouTube, blogs, and social media.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-border",
        name: "Image Border Adder",
        shortDesc: "Add custom colored borders and frames to images.",
        category: "advanced",
        apiEndpoint: "/api/border",
        icon: "🖼️",
        metaTitle: "Add Border to Image Online Free – Image Border Tool",
        metaDesc: "Add borders to images online for free. Choose custom border size, color, and style instantly.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "image-aspect-ratio",
        name: "Aspect Ratio Changer",
        shortDesc: "Change image aspect ratio to 16:9, 4:3, 1:1, and more.",
        category: "advanced",
        apiEndpoint: "/api/resize",
        icon: "📺",
        metaTitle: "Change Image Aspect Ratio Online Free – Aspect Ratio Tool",
        metaDesc: "Change image aspect ratio online for free. Resize to 16:9, 4:3, 1:1, or any custom ratio.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
    {
        slug: "reduce-image-file-size",
        name: "Image File Size Reducer",
        shortDesc: "Reduce image file size for email, web, and uploads.",
        category: "advanced",
        apiEndpoint: "/api/compress",
        icon: "📦",
        metaTitle: "Reduce Image File Size Online Free – Image Size Reducer",
        metaDesc: "Reduce image file size online for free. Compress photos for email, social media, and websites.",
        acceptedFormats: ["image/jpeg", "image/png", "image/webp"],
    },
];

export const TOOL_CATEGORIES = {
    compression: { label: "Image Compression", color: "from-blue-500 to-cyan-500", desc: "Shrink file sizes without sacrificing visual quality" },
    "resize-crop": { label: "Resize & Crop", color: "from-violet-500 to-purple-500", desc: "Change dimensions, crop, rotate, and flip images" },
    conversion: { label: "Image Conversion", color: "from-rose-500 to-pink-500", desc: "Convert between JPEG, PNG, WEBP, and PDF formats" },
    utilities: { label: "Image Utilities", color: "from-amber-500 to-orange-500", desc: "Watermark, blur, color-pick, and inspect image metadata" },
    advanced: { label: "Advanced Tools", color: "from-emerald-500 to-teal-500", desc: "AI background removal, upscaling, filters, and more" },
};

export function getToolBySlug(slug: string): ToolData | undefined {
    return TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: ToolCategory): ToolData[] {
    return TOOLS.filter((t) => t.category === category);
}
